import unittest

from day07.part2 import read_input, process_tachyon

INPUT = """\
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
..............."""


class TestIdValidation(unittest.TestCase):

    def test_input(self):
        res = process_tachyon(INPUT)
        self.assertEqual(40, res)

    def test_file(self):
        f = read_input()
        self.assertTrue(f)
        result = process_tachyon(f)
        self.assertEqual(48989920237096, result)


if __name__ == "__main__":
    unittest.main()
